[package]
name = "fitsio-tools"
version = "0.9.0"
edition = "2021"

[dependencies]
fitsio-pure = { path = "../fitsio-pure", version = "0.9.0" }

[[bin]]
name = "fitsinfo"
path = "src/bin/fitsinfo.rs"

[[bin]]
name = "fitsconv"
path = "src/bin/fitsconv.rs"
